version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    networks:
      - workouts-net
  backend:
    build: ./backend
    image: workouts-backend
    networks:
      - workouts-net
    environment:
      - PORT=5000
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    image: workouts-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
networks:
  workouts-net:
volumes:
  frontend:
